### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Bennet09**
updating my chatbot pop up message

### CODE REVIEW

**Comment by PhilaniMant** [comment]
Your page could use a bit of brighter colors

**Comment by Nondumiso98** [comment]
Your webpage looks perfect

**Comment by Moloko-DevOps95** [comment]
Please make your chatbot responsive and also use an api key or dialog flow

**Review by SiyaxolisVena — COMMENTED** [review]
your chatbot is not responding to my questions

**Pull request merged**
